# Generated by Django 4.1.5 on 2023-01-09 16:04

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", base.models.UserManager()),
            ],
        ),
    ]
