# Generated by Django 4.1.5 on 2023-01-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"verbose_name": "Pricing", "verbose_name_plural": "Pricings"},
        ),
    ]
