# Generated by Django 4.1.5 on 2023-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wsite", "0003_rename_emails_websiteemail_rename_log_websitelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="status",
            field=models.CharField(
                choices=[("down", "Down"), ("up", "Up")], default="up", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="websitelog",
            name="status",
            field=models.CharField(
                choices=[("down", "Down"), ("up", "Up")], default="up", max_length=30
            ),
        ),
    ]
