name: SDTMONITOR CICD workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 1000s
          script: |
            sudo su
            cd /home/ubuntu
            bash update.sh
